### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference                                                  

### ISSUE THREAD

**Issue by ch-muhammad-adil** [FutureMind/recycler-fast-scroll#34]
I am facing this issue, Please assist me...

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnTouchListener(android.view.View$OnTouchListener)' on a null object reference
                                                                         at com.futuremind.recyclerviewfastscroll.FastScroller.initHandleMovement(FastScroller.java:186)
                                                                         at com.futuremind.recyclerviewfastscroll.FastScroller.onLayout(FastScroller.java:162)
                                                                         at android.view.View.layout(View.java:17522)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                         at android.view.View.layout(View.java:17522)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17522)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                         at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
                                                                         at android.view.View.layout(View.java:17522)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                         at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                         at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                         at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1364)
                                                                         at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:846)
                                                                         at android.view.View.layout(View.java:17522)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                         at android.view.View.layout(View.java:17522)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17522)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                         at android.view.View.layout(View.java:17522)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17522)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                         at android.view.View.layout(View.java:17522)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
                                                                         at android.view.View.layout(View.java:17522)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2342)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2069)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)

**Comment by anudeepreddygopu** [comment]
Hey,
did you get any solution. I am facing the same issue.
Thank you,
Anudeep

**Comment by ch-muhammad-adil** [comment]
@anudeepreddygopu  I have used another library.

**Comment by ch-muhammad-adil** [comment]
here you can have look . I have used its code https://github.com/AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller

**Comment by micHar** [comment]
Can you post your code that provoked this error? It's difficult to see what happened without the code.

**Comment by Hitexroid** [comment]
Hi , this is my problem too !
just in some device .

My Xml :

`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />

    <com.futuremind.recyclerviewfastscroll.FastScroller
        android:id="@+id/fastscroll"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_alignParentRight="true"/>
		
	<com.recyclerview.header.RecyclerViewHeader
		android:id="@+id/recyclerHeader"
	    android:layout_width="match_parent"
		android:layout_height="wrap_content"/>

</RelativeLayout>`


when lunch app will crash

**Comment by micHar** [comment]
Thanks for XML, can you also post your Java code which relates to the issue?

**Comment by ch-muhammad-adil** [comment]
This is the fast scroller class just use this or create new one and copy past its code

https://github.com/AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller/blob/master/library/src/main/java/com/lb/recyclerview_fast_scroller/RecyclerViewFastScroller.java

Rest implementation you will find here 
https://github.com/AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller/tree/master/app/src/main

Just have a look on its java code and also on its resource files inside layout and drawables, you just need to copy paste those files. 

Here you will see how he has used that class from the library so you can try this 
https://github.com/AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller/blob/master/app/src/main/res/layout/fragment_recycler_view.xml

Please note that he has used scroller class in the **fragment_recycler_view.xml** . you can see this code 
` <com.lb.recyclerview_fast_scroller.RecyclerViewFastScroller
        android:id="@+id/fastscroller"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_alignBottom="@id/recyclerview"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_alignTop="@id/recyclerview"
        />
 `

you need to change this **com.lb.recyclerview_fast_scroller.RecyclerViewFastScroller** to **YourPackageName.RecyclerViewFastScroller** . I hope you have got me know. 

All you need to do is create your own class of **RecyclerViewFastScroller** and use it like I have explained and like the developer has used in sample app.

**Comment by Hitexroid** [comment]
@micHar 

`relative = (RelativeLayout) LayoutInflater.from(ba.context).inflate(R.layout.recyclerandfastscroll1, null);`
`recyclerView = (RecyclerView) relative.findViewById(R.id.recyclerview);`
`fastScroller = (FastScroller) relative.findViewById(R.id.fastscroll);`

`fastScroller.setRecyclerView(recyclerView);`

**Comment by micHar** [comment]
@Hitexroid you don't `setAdapter` before `setRecyclerView`. See the [readme](https://github.com/FutureMind/recycler-fast-scroll#minimal-working-example).

        recyclerView = (RecyclerView) findViewById(R.id.recyclerview);
        fastScroller = (FastScroller) findViewById(R.id.fastscroll);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setAdapter(adapter);

        //has to be called AFTER RecyclerView.setAdapter()
        fastScroller.setRecyclerView(recyclerView);

**Comment by Hitexroid** [comment]
no , i called `setRecyclerView ` after `setAdapter`

and i said "crash in some device , not all device" in may `xml` post .

**Comment by micHar** [comment]
OK, I did not notice because of the strange formatting.

On what devices does it crash then? Manufacturer, Android version etc. Can you repeat it consistently on an emulator?

**Comment by micHar** [comment]
The question is how is the viewProvider null there. `onLayout` is not called before the view started inflating, viewProvider should be already there by that time, I suppose.

**Comment by micHar** [comment]
I mean, what you wrote would be a good quickfix, but I would rather understand the issue and fix it properly.

**Comment by micHar** [comment]
Alright, the viewProvider was being set at latest inside `setRecyclerView(recyclerView);`. So the onLayout could apparently be called earlier which caused NPE in some specific circumstances (specific devices? - I cannot repeat it).

Therefore, now I create the default viewprovider in the contructor, so there should be no way it's null in `onLayout`. I released new version 0.2.5. I'm closing it now, reopen if you still experience this issue. Thanks!

**Comment by billrancho** [comment]
@micHar  I am still facing this issue on 0.2.5. 
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.RecyclerView.computeVerticalScrollOffset()' on a null object reference

**Comment by ayush9** [comment]
Same Error: 
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.RecyclerView.computeVerticalScrollOffset()' on a null object reference

**Comment by arjun902** [comment]
Hello everyone, I am facing this error ... please help me

01-14 00:43:10.424 4486-4486/? E/libprocessgroup: failed to make and chown /acct/uid_10058: Read-only file system
01-14 00:43:25.937 4486-4486/com.example.user.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.example.user.myapplication, PID: 4486
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.user.myapplication/com.example.user.myapplication.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                                  at com.example.user.myapplication.MainActivity.onCreate(MainActivity.java:56)
                                                                                  at android.app.Activity.performCreate(Activity.java:5990)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 



My Java Code is here

package com.example.user.myapplication;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {
    EditText num1, num2;
    TextView result;
    Button add, subtract, multiply, divide;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        num1 = findViewById(R.id.number1);
        num2 = findViewById(R.id.number2);
        result = findViewById(R.id.Result);
        add = findViewById(R.id.buttonAddAdd);
        subtract = findViewById(R.id.buttonSubtract);
        add = findViewById(R.id.buttonMultiply);
        add = findViewById(R.id.buttonDivide);

        add.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (num1.getText() != null && num2.getText() != null) {
                    double n1 = Double.parseDouble(num1.getText().toString());
                    double n2 = Double.parseDouble(num2.getText().toString());
                    double res = n1 + n2;
                    result.setText(String.valueOf(res));
                } else {
                    Toast.makeText(view.getContext(), "please enter the number properly", Toast.LENGTH_SHORT).show();

                }
            }
        });
        subtract.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (num1.getText() != null && num2.getText() != null) {
                    double n1 = Double.parseDouble(num1.getText().toString());
                    double n2 = Double.parseDouble(num2.getText().toString());
                    double res = n1 - n2;
                    result.setText(String.valueOf(res));
                } else {
                    Toast.makeText(view.getContext(), "please enter the number properly", Toast.LENGTH_SHORT).show();

                }
            }
        });
        multiply.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (num1.getText() != null && num2.getText() != null) {
                    double n1 = Double.parseDouble(num1.getText().toString());
                    double n2 = Double.parseDouble(num2.getText().toString());
                    double res = n1 * n2;
                    result.setText(String.valueOf(res));
                } else {
                    Toast.makeText(view.getContext(), "please enter the number properly", Toast.LENGTH_SHORT).show();

                }
            }
        });
        divide.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (num1.getText() != null && num2.getText() != null) {
                    double n1 = Double.parseDouble(num1.getText().toString());
                    double n2 = Double.parseDouble(num2.getText().toString());
                    double res = n1 / n2;
                    result.setText(String.valueOf(res));
                } else {
                    Toast.makeText(view.getContext(), "please enter the number properly", Toast.LENGTH_SHORT).show();
                }
            }
        });
    }
}

**Comment by fitnessthetic** [comment]
same problem..
![image](https://user-images.githubusercontent.com/35904830/35597033-8f443fb6-062d-11e8-8547-b7f227db467c.png)

**Comment by tgvdinesh** [comment]
`on a null object reference`. When you try to do a method call over a null object then you'll get the error.

In most of the case `findViewByID` will return null if you don't call `setContextView` before your `findViewByID` call.

**Comment by altotunchitoo** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.recyclerview.widget.RecyclerView.computeVerticalScrollOffset()' on a null object reference
        at com.futuremind.recyclerviewfastscroll.RecyclerViewScrollListener.updateHandlePosition(RecyclerViewScrollListener.java:47)

**I'm facing the same error when there are no rows in the recycler view.**
:-)
